name: AI Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**.py'
      - 'app/**'
      - 'tests/**'
      - 'migration/**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    name: OpenAI Code Review
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get PR diff
        id: get-diff
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "base_sha=$(git rev-parse origin/${{ github.base_ref }})" >> $GITHUB_OUTPUT
          echo "head_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      
      - name: OpenAI Code Review
        uses: yunyunlee/openai-code-review-action@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4o"
          exclude: |
            **/*.json
            **/*.md
            **/*.txt
            **/*.yaml
            **/*.yml
            **/*.lock
            **/requirements*.txt
            **/__pycache__/**
            **/*.pyc
            **/migrations/**
            **/.env*
            **/venv/**
            **/.venv/**
            **/htmlcov/**
            **/.pytest_cache/**
            **/.mypy_cache/**
            **/.ruff_cache/**
            
      - name: Comment PR Summary
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            try {
              await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: prNumber,
                body: `## 🤖 AI Code Review Complete
                
                The automated code review has been performed. Please check the inline comments above for:
                - Code quality suggestions
                - Potential bugs or issues
                - Best practice recommendations
                - Performance improvements
                - Security considerations
                
                Remember to address critical feedback before merging.`
              });
            } catch (error) {
              console.error('Failed to post summary comment:', error);
            }