name: OpenAI Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: AI Code Reviewer
        uses: yunyunlee/openai-code-review-action@v2.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4o"
          exclude: "**/*.json, **/*.md, **/*.txt, **/*.yaml, **/*.yml, **/migrations/**, **/*.lock, **/requirements.txt"