name: AI Code Reviewer
# Updated to use correct action v2.7.1

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: OpenAI GPT Code Review Action
        uses: Ostrich-Cyber-Risk/ai-codereviewer@v2.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4o"
          exclude: "**/*.json, **/*.md, **/*.txt, **/*.yaml, **/*.yml, **/migrations/**, **/*.lock, **/requirements.txt"